feat(core): #41 improve logging
NethermindEth/dotnet-libp2p pull request #47
Opened 2023-09-22 21:34 UTC by chertby

#41

2023-09-26 11:30 UTC, flcl42 requested changes

2023-09-26 11:30 UTC, flcl42 commented on src/libp2p/Libp2p.Core/ChannelFactory.cs
> +        _logger?.ChanCreated(chan.Id);
`ChannelCreated`

2023-09-26 20:26 UTC, chertby commented on src/libp2p/Libp2p.Core/ChannelFactory.cs
> +        _logger?.ChanCreated(chan.Id);
done

2023-09-26 20:27 UTC, chertby commented on src/libp2p/Libp2p.Core/ChannelFactory.cs
> +                _logger?.LogCompletedUnsuccessfully(nameof(SubListen), chan.Id, subProtocol.Id, t.Exception, t.Exception?.Message ?? "unknown");
done

2023-09-27 09:25 UTC, flcl42 approved these changes

2023-09-27 09:46 UTC, merged